name: GitHub CI

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run cargo clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Run Rust formatting checks
      run: cargo fmt --all --check
